import { Card, Icon, Text } from "@ui-kitten/components";
import { KeyboardAwareScrollView } from "react-native-keyboard-aware-scroll-view";
import { Dimensions, StyleSheet, View } from 'react-native'
const windowHeight = Dimensions.get('window').height;

export default function TermsModal({ setVisible }) {
    return (
        <Card disabled={true}>
            <KeyboardAwareScrollView style={{ maxHeight: windowHeight - 150 }}>
                <View style={{ width: 30, height: 30, marginLeft: "auto" }}>
                    <Icon
                        name="close-outline"
                        onPress={() => {
                            setVisible(false);
                        }}
                    />
                </View>
                <Text style={{ marginVertical: 10 }} category="h5">Terms and Conditions</Text>
                <Text style={styles.body} category="p1">1. CQ Painting, Inc. shall begin work under this agreement and continue the work hereunder to completion within a reasonable time, subject to such delays as are permissible under this contract. Owner shall obtain a valid building permit from the appropriate Public Authority if such building permit is required. If requested by Owner, CQ Painting, Inc. will obtain any required building permit. Any fee or charge which must be paid to the Public Authority in connection with the work will be paid by owner unless provide otherwise under this contract.</Text>
                <Text style={styles.body} category="p1"> 2. CQ Painting, Inc. shall pay all valid bills and charges for materials and labor arising out of the construction of the structure and will hold owner of the property free and harmless against all liens and claims of lien for labor and material filed against the property.</Text>
                <Text style={styles.body} category="p1">3. Unless otherwise specified, the contract price is based upon Owner's representation that there are no conditions preventing CQ Painting, Inc. from proceeding with usual installation procedures for the materials required under this contract. Further, Owner represents that he will relocate furniture, clothing, draperies, personal effects, all personal property, plants, trees, and bushes prior to the beginning of work so that CQ Painting, Inc. has free access to portions of the area where work is to be done. In the event that Owner fails to relocate any items as provided hereunder, CQ Painting, Inc. may relocate or move any of Owner's property as may be required and is not responsible for damage thereto which may result during prosecution of the work.</Text>
                <Text style={styles.body} category="p1">4. Owner agrees to pay CQ Painting, Inc. his normal selling price for all additions, alterations or deviations. No additional work shall be done without the prior written authorization of Owner. Any such authorization shall be on a change order form, approved by both parties, which shall become a part of this Contract.
                    Where such additional work is added to this Contract shall apply equally to such additional work.</Text>
                <Text style={styles.body} category="p1"> 5. CQ Painting, Inc. shall not be responsible for any damage occasioned by the Owner or Owner's agent, rain, windstorm, acts of God, or other causes beyond the control of CQ Painting, Inc., unless otherwise herein provided or unless he is obligated by the terms hereof to provided insurance against such hazard. CQ Painting, Inc. shall not be liable for damages or defects resulting from work done by subcontractors contracted by Owner. In the event Owner authorizes access through adjacent properties for CQ Painting, Inc.'s use during construction, Owner is required to obtain permission from the owners) of the adjacent properties for such access. Owner agrees to be responsible and to hold CQ Painting, Inc. harmless and accept any risks resulting from access through adjacent properties.</Text>
                <Text style={styles.body} category="p1"> 6. The time during which CQ Painting, Inc. is delayed in his work by (a) the acts of Owner or his agents, subcontractors or employees or those claiming under agreement with or grant from Owner, or by (b) the Acts of God which CQ Painting, Inc. could not have reasonable foreseen and provided against, or by (c)stormy or inclement weather which necessarily delays the work, or by (d) any strikes, boycotts or like obstructive actions by employees or labor organizations and which are beyond the control of CQ Painting, Inc. and which he cannot reasonable overcome, or by (e) extra work requested by the Owner, or by (1) failure of Owner to promptly pay for any extra work as authorized, shall be added to the time for completion by a fair and reasonable allowance.</Text>
                <Text style={styles.body} category="p1"> 7. CQ Painting, Inc. shall at his own expense carry all workers' compensation insurance and liability insurance necessary for the full protection of CQ Painting.
                    Inc. and Owner during the progress of the work. Certificates of such insurance shall be filed with Owner and with said Lien Holder if Owner and Lien Holder so require. Owner agrees to procure at his own expense, prior to the commencement of any work, fire insurance with Course of Construction, all Physical Loss and Vandalism and Malicious Mischief clauses attached in a sum equal to the total cost of the improvements.</Text>
                <Text style={styles.body} category="p1">8. Where colors, textures, shades or hues are to be matched, CQ Painting, Inc. shall make every reasonable effort to do so using standard materials, but does not guarantee a perfect match. At owner's written request, CQ Painting, Inc. will provided a sample of any color, texture, shaded or hue to be used under this contract for approval or disapproval by Owner. A small fee will be charge for sample color. If Owner does not so request, CQ Painting, Inc. is authorized to apply manufacturer's standard colors, textures, shades and hues as identified in this contract and is not responsible for any discrepancy between the manufacturer's sample and the materials as applied.</Text>
                <Text style={styles.body} category="p1">9. CQ Painting, Inc. makes no warranty, express or implied (including warranty of fitness for purpose and merchantability). Any warranty or limited warranty shall be as provided by the manufacturer or the products and materials used.</Text>
                <Text style={styles.body} category="p1">10. Any controversy or claim arising out of or relating to this contract, shall be settled by arbitration in accordance with the Rules of the American Arbitration Association, and judgment in any Court having jurisdiction.</Text>
                <Text style={styles.body} category="p1">11. Should either party hereto bring suit in court to enforce the terms of this agreement, any judgment awarded shall include court costs and reasonable attorney's fees to the successful party plus interest at the legal rate.</Text>
                <Text style={styles.body} category="p1">12. Owner grants to CQ Painting, Inc. and CQ Painting, Inc.'s employees and subcontractors the right to enter the premises.</Text>
                <Text style={styles.body} category="p1"> 13. The Owner is solely responsible for providing CQ Painting, Inc. prior to the commencing of work with such water, electricity, heater and refuse removal service at the job site as may require by CQ Painting, Inc. to carry out this contract. Owner shall provide a toilet during the course of construction when required by law. CQ Painting, Inc. shall leave living areas "broom clean" at the completion of work</Text>
                <Text style={styles.body} category="p1">14. Work shall be completed and CQ Painting, Inc. shall be entitled to prompt payment in full when the work described in this contract has been performed. CQ Painting, Inc. is not obligated to do any work or perform any service except as expressly provided in this agreement. If, after CQ Painting, Inc. has declared the work completed, Owner claims that work still remains to be done, Owner agrees to make prompt payment of the full contract amount less only an amount needed to complete the work. Upon completion of any corrective work claimed by Owner, CQ Painting, Inc. shall be entitled to payment of the full contract amount.</Text>
                <Text style={styles.body} category="p1">15. CQ Painting, Inc. has the right to subcontract any part, or all, of the work herein agreed to be performed.</Text>
                <Text style={styles.body} category="p1">16. CQ Painting, Inc. shall have no liability for correcting any existing defect which is recognized during the course of work.</Text>
                <Text style={styles.body} category="p1">17. Owner hereby grants to CQ Painting, Inc. the right to display signs and advertise at the building, work side until all work is completed and payment in full has been made.</Text>
                <Text style={styles.body} category="p1">18. CQ Painting, Inc. shall have the right to stop work and keep the job idle if payment are not made to him when due. If any payment are not made to CQ Painting, Inc. when due, owner shall pay to CQ Painting, Inc. and additional charge of 10% of the amount of such payment.</Text>
                <Text style={styles.body} category="p1">19. Within ten days after execution of this Contract, CQ Painting, Inc. shall have the right to cancel this Contract should he determine that there is any uncertainty that all payment due under this contract will be made when due or that an error has been made in computing the cost of completing the work.</Text>
                <Text style={styles.body} category="p1">20. This agreement constitutes the entire contract and the parties are not bound by oral expression or representation by any party or agent or either party.</Text>
                <Text style={styles.body} category="p1">21. The price quoted for completion of the structure is subject to change to the extent of any difference in the cost of labor and materials as of this date and the actual cost to CQ Painting, Inc. at the time materials are purchased and work is done.</Text>
                <Text style={styles.body} category="p1">22. CQ Painting, Inc. is not responsible for labor or materials furnished by Owner or anyone working under the direction of the Owner and any loss or additional work that results therefrom shall be the responsibility of the Owner.</Text>
                <Text style={styles.body} category="p1" >23. Job labor comes with two years warranty, restrictions apply.</Text>
                <Text style={styles.body} category="p1">24. No action arising from or related to the contract, or the performance thereof, shall be commenced by either party against the other more than two years after the completion or cessation of work under this Contract. This limitation applies to all actions of any character, whether sounding in contract, tort, or otherwise.</Text>
                <Text style={styles.body} category="p1">25. CQ Painting, Inc. agrees to complete the work in a substantial and workmanlike manner but is not responsible for failures or defects that result from work done by others prior, at the time of or subsequent to work done under this agreement, failure to keep gutters, downspouts and valleys reasonable clear of leaves or obstructions, failure of the Owner to authorize CQ Painting, Inc. to undertake needed repairs or replacement of water-damaged, blistered, peeling or otherwise deteriorating surfaces. CQ Painting, Inc. is not liable for any act of negligence or misuse by the Owner or any other party.</Text>
            </KeyboardAwareScrollView>
        </Card>
    )
}

const styles = StyleSheet.create({
    body: {
        marginTop: 10,
    }
})